import { PathMetadata } from "@/app/utils/path";
import { BRAND_COLOURS } from "@blueshift-gg/ui-components";

export const paths: PathMetadata[] = [
  {
    slug: "web3-fullstack-beginner",
    language: "General",
    color: BRAND_COLOURS.general,
    difficulty: 1,
    isFeatured: true,
    estimatedHours: 80,
    steps: [
      { type: "course", slug: "introduction-to-blockchain-and-solana" },
      { type: "course", slug: "introduction-to-ethereum" },
      { type: "course", slug: "flip-coins-on-evm" },
      { type: "course", slug: "your-first-solana-fullstack-dapp" },
      { type: "challenge", slug: "anchor-flip-coins" },
      { type: "course", slug: "introduction-to-uniswap" },
      { type: "challenge", slug: "anchor-uniswap-v2" },
    ],
  },
  // {
  //   slug: "solana-developer-foundations",
  //   language: "General",
  //   color: BRAND_COLOURS.general,
  //   difficulty: 1,
  //   isFeatured: true,
  //   estimatedHours: 8,
  //   steps: [
  //     { type: "course", slug: "introduction-to-blockchain-and-solana" },
  //     { type: "course", slug: "tokens-on-solana" },
  //     { type: "course", slug: "nfts-on-solana" },
  //   ],
  // },
  // {
  //   slug: "anchor-mastery",
  //   language: "Anchor",
  //   color: BRAND_COLOURS.anchor,
  //   difficulty: 2,
  //   isFeatured: true,
  //   estimatedHours: 20,
  //   steps: [
  //     { type: "course", slug: "introduction-to-blockchain-and-solana" },
  //     { type: "course", slug: "anchor-for-dummies" },
  //     { type: "challenge", slug: "anchor-vault" },
  //     { type: "course", slug: "spl-token-with-anchor" },
  //     { type: "challenge", slug: "anchor-escrow" },
  //     { type: "course", slug: "token-2022-with-anchor" },
  //     { type: "challenge", slug: "anchor-flash-loan" },
  //   ],
  // },
  // {
  //   slug: "native-rust-developer",
  //   language: "Rust",
  //   color: BRAND_COLOURS.rust,
  //   difficulty: 3,
  //   isFeatured: true,
  //   estimatedHours: 30,
  //   steps: [
  //     { type: "course", slug: "introduction-to-blockchain-and-solana" },
  //     { type: "course", slug: "pinocchio-for-dummies" },
  //     { type: "challenge", slug: "pinocchio-vault" },
  //     { type: "course", slug: "token-2022-program" },
  //     { type: "challenge", slug: "pinocchio-escrow" },
  //     { type: "course", slug: "testing-with-mollusk" },
  //     { type: "challenge", slug: "pinocchio-amm" },
  //   ],
  // },
  {
    slug: "frontend-dapp-beginner",
    language: "Typescript",
    color: BRAND_COLOURS.typescript,
    difficulty: 1,
    isFeatured: true,
    estimatedHours: 15,
    steps: [
      { type: "course", slug: "introduction-to-blockchain-and-solana" },
      { type: "course", slug: "create-evm-dapp-with-wagmi-and-rainbowkit" },
      { type: "course", slug: "build-a-solana-explorer" },
      { type: "course", slug: "tokens-on-solana" },
      { type: "course", slug: "spl-token-with-web3js" },
      { type: "course", slug: "token-2022-with-web3js" },
    ],
  },
  {
    slug: "backend-web3-beginner",
    language: "General",
    color: BRAND_COLOURS.general,
    difficulty: 1,
    isFeatured: true,
    estimatedHours: 15,
    steps: [
      { type: "course", slug: "introduction-to-blockchain-and-solana" },
      { type: "course", slug: "tokens-on-solana" },
      { type: "course", slug: "spl-token-with-web3js" },
      { type: "course", slug: "token-2022-with-web3js" },
    ],
  },
  // {
  //   slug: "security-specialist",
  //   language: "General",
  //   color: BRAND_COLOURS.general,
  //   difficulty: 2,
  //   isFeatured: true,
  //   estimatedHours: 12,
  //   steps: [
  //     { type: "course", slug: "introduction-to-blockchain-and-solana" },
  //     { type: "course", slug: "program-security" },
  //     { type: "course", slug: "secp256r1-on-solana" },
  //     { type: "course", slug: "winternitz-signatures-on-solana" },
  //   ],
  // },
  // {
  //   slug: "testing-and-tooling",
  //   language: "General",
  //   color: BRAND_COLOURS.general,
  //   difficulty: 2,
  //   isFeatured: false,
  //   estimatedHours: 10,
  //   steps: [
  //     { type: "course", slug: "testing-with-mollusk" },
  //     { type: "course", slug: "testing-with-litesvm" },
  //     { type: "course", slug: "testing-with-surfpool" },
  //     { type: "course", slug: "create-your-sdk-with-codama" },
  //   ],
  // },
  // {
  //   slug: "advanced-low-level",
  //   language: "Assembly",
  //   color: BRAND_COLOURS.assembly,
  //   difficulty: 4,
  //   isFeatured: false,
  //   estimatedHours: 25,
  //   steps: [
  //     { type: "course", slug: "pinocchio-for-dummies" },
  //     { type: "course", slug: "introduction-to-assembly" },
  //     { type: "course", slug: "instruction-introspection" },
  //     { type: "challenge", slug: "pinocchio-vault" },
  //     { type: "challenge", slug: "pinocchio-escrow" },
  //     { type: "challenge", slug: "pinocchio-amm" },
  //   ],
  // },
  // {
  //   slug: "token-developer",
  //   language: "General",
  //   color: BRAND_COLOURS.general,
  //   difficulty: 2,
  //   isFeatured: false,
  //   estimatedHours: 18,
  //   steps: [
  //     { type: "course", slug: "tokens-on-solana" },
  //     { type: "course", slug: "spl-token-with-web3js" },
  //     { type: "course", slug: "spl-token-with-anchor" },
  //     { type: "course", slug: "token-2022-program" },
  //     { type: "course", slug: "token-2022-with-web3js" },
  //     { type: "course", slug: "token-2022-with-anchor" },
  //   ],
  // },
  // {
  //   slug: "payments-and-commerce",
  //   language: "General",
  //   color: BRAND_COLOURS.general,
  //   difficulty: 1,
  //   isFeatured: false,
  //   estimatedHours: 6,
  //   steps: [
  //     { type: "course", slug: "introduction-to-blockchain-and-solana" },
  //     { type: "course", slug: "tokens-on-solana" },
  //     { type: "course", slug: "solana-pay" },
  //   ],
  // },
];
